spring:
  application:
    name: microService

server:  
  port: ${PORT:3333}

# Discovery Server Access
eureka:  
  client:
    registerWithEureka: true
    fetchRegistry: true	
    serviceUrl:
      defaultZone: http://discovery-server:1111/eureka/
    instance:
     hostname: localhost